/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--bg-color)',
        accent: 'var(--bg-color-1)',
        decend: 'var(--bg-color-2)',
        secondary: 'var(--bg-color-3)',
        primaryFg: 'var(--fg-color)',
        accentFg: 'var(--fg-color-0)',
        decendFg: 'var(--fg-color-2)',
        secondaryFg: 'var(--fg-color-3)',
        red_background: 'var(--red_background)',
        pink_background: 'var(--pink_background)',
        blue_background: 'var(--blue_background)',
        purple_background: 'var(--purple_background)',
        teal_background: 'var(--teal_background)',
        yellow_background: 'var(--yellow_background)',
        orange_background: 'var(--orange_background)',
        brown_background: 'var(--brow_background)',
        gray_background: 'var(--gray_background)',
        red_background_co: 'var(--red_background_co)',
        pink_background_co: 'var(--pink_background_co)',
        blue_background_co: 'var(--blue_background_co)',
        purple_background_co: 'var(--purple_background_co)',
        teal_background_co: 'var(--teal_background_co)',
        yellow_background_co: 'var(--yellow_background_co)',
        orange_background_co: 'var(--orange_background_co)',
        brown_background_co: 'var(--brow_background_co)',
        gray_background_co: 'var(--gray_background_co)',
        item_blue: 'var(--item-blue)',
        item_orange: 'var(--item-orange)',
        item_green: 'var(--item-green)',
        item_pink: 'var(--item-pink)',
        item_brown: 'var(--item-brown)',
        item_red: 'var(--item-red)',
        item_yellow: 'var(--item-yellow)',
        item_default: 'var(--item-default)',
        item_purple: 'var(--item-purple)',
        item_gray: 'var(--item-gray)',
        colours: {
          ashley: 'var(--ashley)',
          red: 'var(--red)',
          pink: 'var(--pink)',
          blue: 'var(--blue)',
          purple: 'var(--purple)',
          teal: 'var(--teal)',
          yellow: 'var(--yellow)',
          orange: 'var(--orange)',
          brown: 'var(--brown)',
          gray: 'var(--gray)',
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
